// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: message.proto

package imv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_AUDIO       MessageType = 2
	MessageType_MESSAGE_TYPE_RICH_TEXT   MessageType = 3
	MessageType_MESSAGE_TYPE_SYSTEM      MessageType = 4
	MessageType_MESSAGE_TYPE_ACK         MessageType = 5
	MessageType_MESSAGE_TYPE_JOIN_ROOM   MessageType = 6
	MessageType_MESSAGE_TYPE_LEAVE_ROOM  MessageType = 7
	MessageType_MESSAGE_TYPE_HEARTBEAT   MessageType = 8
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_AUDIO",
		3: "MESSAGE_TYPE_RICH_TEXT",
		4: "MESSAGE_TYPE_SYSTEM",
		5: "MESSAGE_TYPE_ACK",
		6: "MESSAGE_TYPE_JOIN_ROOM",
		7: "MESSAGE_TYPE_LEAVE_ROOM",
		8: "MESSAGE_TYPE_HEARTBEAT",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_AUDIO":       2,
		"MESSAGE_TYPE_RICH_TEXT":   3,
		"MESSAGE_TYPE_SYSTEM":      4,
		"MESSAGE_TYPE_ACK":         5,
		"MESSAGE_TYPE_JOIN_ROOM":   6,
		"MESSAGE_TYPE_LEAVE_ROOM":  7,
		"MESSAGE_TYPE_HEARTBEAT":   8,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 用户角色枚举
type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_MODERATOR   UserRole = 2
	UserRole_USER_ROLE_ADMIN       UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_MODERATOR",
		3: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_MODERATOR":   2,
		"USER_ROLE_ADMIN":       3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 转写状态枚举
type TranscriptStatus int32

const (
	TranscriptStatus_TRANSCRIPT_STATUS_UNSPECIFIED TranscriptStatus = 0
	TranscriptStatus_TRANSCRIPT_STATUS_PENDING     TranscriptStatus = 1
	TranscriptStatus_TRANSCRIPT_STATUS_PROCESSING  TranscriptStatus = 2
	TranscriptStatus_TRANSCRIPT_STATUS_COMPLETED   TranscriptStatus = 3
	TranscriptStatus_TRANSCRIPT_STATUS_FAILED      TranscriptStatus = 4
)

// Enum value maps for TranscriptStatus.
var (
	TranscriptStatus_name = map[int32]string{
		0: "TRANSCRIPT_STATUS_UNSPECIFIED",
		1: "TRANSCRIPT_STATUS_PENDING",
		2: "TRANSCRIPT_STATUS_PROCESSING",
		3: "TRANSCRIPT_STATUS_COMPLETED",
		4: "TRANSCRIPT_STATUS_FAILED",
	}
	TranscriptStatus_value = map[string]int32{
		"TRANSCRIPT_STATUS_UNSPECIFIED": 0,
		"TRANSCRIPT_STATUS_PENDING":     1,
		"TRANSCRIPT_STATUS_PROCESSING":  2,
		"TRANSCRIPT_STATUS_COMPLETED":   3,
		"TRANSCRIPT_STATUS_FAILED":      4,
	}
)

func (x TranscriptStatus) Enum() *TranscriptStatus {
	p := new(TranscriptStatus)
	*p = x
	return p
}

func (x TranscriptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscriptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (TranscriptStatus) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x TranscriptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscriptStatus.Descriptor instead.
func (TranscriptStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

// 健康状态枚举
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED     HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING         HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING     HealthStatus = 2
	HealthStatus_HEALTH_STATUS_SERVICE_UNKNOWN HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
		3: "HEALTH_STATUS_SERVICE_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED":     0,
		"HEALTH_STATUS_SERVING":         1,
		"HEALTH_STATUS_NOT_SERVING":     2,
		"HEALTH_STATUS_SERVICE_UNKNOWN": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[3].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[3]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

// 消息请求
type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=im.v1.MessageType" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *MessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MessageRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 消息响应
type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=im.v1.MessageType" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AckRequired   bool                   `protobuf:"varint,8,opt,name=ack_required,json=ackRequired,proto3" json:"ack_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageResponse) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *MessageResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageResponse) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *MessageResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MessageResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MessageResponse) GetAckRequired() bool {
	if x != nil {
		return x.AckRequired
	}
	return false
}

// 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=im.v1.MessageType" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AckRequired   bool                   `protobuf:"varint,6,opt,name=ack_required,json=ackRequired,proto3" json:"ack_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *SendMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SendMessageRequest) GetAckRequired() bool {
	if x != nil {
		return x.AckRequired
	}
	return false
}

// 发送消息响应
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *ResponseStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SendMessageResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// 加入房间请求
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 加入房间响应
type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	OnlineUsers   []string               `protobuf:"bytes,3,rep,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *JoinRoomResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

func (x *JoinRoomResponse) GetOnlineUsers() []string {
	if x != nil {
		return x.OnlineUsers
	}
	return nil
}

// 离开房间请求
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// 离开房间响应
type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveRoomResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// 获取房间信息请求
type GetRoomInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoRequest) Reset() {
	*x = GetRoomInfoRequest{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoRequest) ProtoMessage() {}

func (x *GetRoomInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRoomInfoRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoomInfoRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取房间信息响应
type GetRoomInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	Users         []*RoomUser            `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomInfoResponse) Reset() {
	*x = GetRoomInfoResponse{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomInfoResponse) ProtoMessage() {}

func (x *GetRoomInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRoomInfoResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoomInfoResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetRoomInfoResponse) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

func (x *GetRoomInfoResponse) GetUsers() []*RoomUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// 房间信息
type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Config        *RoomConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActive    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	MessageCount  int64                  `protobuf:"varint,7,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	UserCount     int32                  `protobuf:"varint,8,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoomInfo) GetConfig() *RoomConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RoomInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomInfo) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *RoomInfo) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *RoomInfo) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

// 房间配置
type RoomConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxUsers           int32                  `protobuf:"varint,1,opt,name=max_users,json=maxUsers,proto3" json:"max_users,omitempty"`
	Persistent         bool                   `protobuf:"varint,2,opt,name=persistent,proto3" json:"persistent,omitempty"`
	MessageTtlSeconds  int64                  `protobuf:"varint,3,opt,name=message_ttl_seconds,json=messageTtlSeconds,proto3" json:"message_ttl_seconds,omitempty"`
	IdleTimeoutSeconds int64                  `protobuf:"varint,4,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	AllowAudio         bool                   `protobuf:"varint,5,opt,name=allow_audio,json=allowAudio,proto3" json:"allow_audio,omitempty"`
	AllowRichText      bool                   `protobuf:"varint,6,opt,name=allow_rich_text,json=allowRichText,proto3" json:"allow_rich_text,omitempty"`
	AutoTranscribe     bool                   `protobuf:"varint,7,opt,name=auto_transcribe,json=autoTranscribe,proto3" json:"auto_transcribe,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoomConfig) Reset() {
	*x = RoomConfig{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomConfig) ProtoMessage() {}

func (x *RoomConfig) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomConfig.ProtoReflect.Descriptor instead.
func (*RoomConfig) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *RoomConfig) GetMaxUsers() int32 {
	if x != nil {
		return x.MaxUsers
	}
	return 0
}

func (x *RoomConfig) GetPersistent() bool {
	if x != nil {
		return x.Persistent
	}
	return false
}

func (x *RoomConfig) GetMessageTtlSeconds() int64 {
	if x != nil {
		return x.MessageTtlSeconds
	}
	return 0
}

func (x *RoomConfig) GetIdleTimeoutSeconds() int64 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *RoomConfig) GetAllowAudio() bool {
	if x != nil {
		return x.AllowAudio
	}
	return false
}

func (x *RoomConfig) GetAllowRichText() bool {
	if x != nil {
		return x.AllowRichText
	}
	return false
}

func (x *RoomConfig) GetAutoTranscribe() bool {
	if x != nil {
		return x.AutoTranscribe
	}
	return false
}

// 房间用户
type RoomUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=im.v1.UserRole" json:"role,omitempty"`
	Muted         bool                   `protobuf:"varint,4,opt,name=muted,proto3" json:"muted,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomUser) Reset() {
	*x = RoomUser{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomUser) ProtoMessage() {}

func (x *RoomUser) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomUser.ProtoReflect.Descriptor instead.
func (*RoomUser) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *RoomUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoomUser) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *RoomUser) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *RoomUser) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// 语音转写请求
type TranscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptRequest) Reset() {
	*x = TranscriptRequest{}
	mi := &file_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptRequest) ProtoMessage() {}

func (x *TranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptRequest.ProtoReflect.Descriptor instead.
func (*TranscriptRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *TranscriptRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *TranscriptRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 语音转写响应
type TranscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Transcription *Transcription         `protobuf:"bytes,2,opt,name=transcription,proto3" json:"transcription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptResponse) Reset() {
	*x = TranscriptResponse{}
	mi := &file_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptResponse) ProtoMessage() {}

func (x *TranscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptResponse.ProtoReflect.Descriptor instead.
func (*TranscriptResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

func (x *TranscriptResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TranscriptResponse) GetTranscription() *Transcription {
	if x != nil {
		return x.Transcription
	}
	return nil
}

// 转写结果
type Transcription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Status        TranscriptStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=im.v1.TranscriptStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcription) Reset() {
	*x = Transcription{}
	mi := &file_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcription) ProtoMessage() {}

func (x *Transcription) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcription.ProtoReflect.Descriptor instead.
func (*Transcription) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{15}
}

func (x *Transcription) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *Transcription) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transcription) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Transcription) GetStatus() TranscriptStatus {
	if x != nil {
		return x.Status
	}
	return TranscriptStatus_TRANSCRIPT_STATUS_UNSPECIFIED
}

func (x *Transcription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transcription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 音频上传请求
type UploadAudioRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadAudioRequest_Metadata
	//	*UploadAudioRequest_Chunk
	Data          isUploadAudioRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAudioRequest) Reset() {
	*x = UploadAudioRequest{}
	mi := &file_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAudioRequest) ProtoMessage() {}

func (x *UploadAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAudioRequest.ProtoReflect.Descriptor instead.
func (*UploadAudioRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{16}
}

func (x *UploadAudioRequest) GetData() isUploadAudioRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadAudioRequest) GetMetadata() *AudioMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadAudioRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadAudioRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadAudioRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadAudioRequest_Data interface {
	isUploadAudioRequest_Data()
}

type UploadAudioRequest_Metadata struct {
	Metadata *AudioMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadAudioRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadAudioRequest_Metadata) isUploadAudioRequest_Data() {}

func (*UploadAudioRequest_Chunk) isUploadAudioRequest_Data() {}

// 音频元数据
type AudioMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Duration      float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioMetadata) Reset() {
	*x = AudioMetadata{}
	mi := &file_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMetadata) ProtoMessage() {}

func (x *AudioMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMetadata.ProtoReflect.Descriptor instead.
func (*AudioMetadata) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{17}
}

func (x *AudioMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AudioMetadata) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AudioMetadata) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AudioMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AudioMetadata) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// 音频上传响应
type UploadAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AudioId       string                 `protobuf:"bytes,2,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,3,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAudioResponse) Reset() {
	*x = UploadAudioResponse{}
	mi := &file_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAudioResponse) ProtoMessage() {}

func (x *UploadAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAudioResponse.ProtoReflect.Descriptor instead.
func (*UploadAudioResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{18}
}

func (x *UploadAudioResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UploadAudioResponse) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *UploadAudioResponse) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

// 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{19}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=im.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{20}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 响应状态
type ResponseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseStatus) Reset() {
	*x = ResponseStatus{}
	mi := &file_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatus) ProtoMessage() {}

func (x *ResponseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatus.ProtoReflect.Descriptor instead.
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{21}
}

func (x *ResponseStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseStatus) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// 文本消息内容
type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{22}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 音频消息内容
type AudioContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	AudioUrl      string                 `protobuf:"bytes,2,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	Duration      float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Transcription string                 `protobuf:"bytes,6,opt,name=transcription,proto3" json:"transcription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioContent) Reset() {
	*x = AudioContent{}
	mi := &file_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioContent) ProtoMessage() {}

func (x *AudioContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioContent.ProtoReflect.Descriptor instead.
func (*AudioContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{23}
}

func (x *AudioContent) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *AudioContent) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *AudioContent) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AudioContent) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AudioContent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AudioContent) GetTranscription() string {
	if x != nil {
		return x.Transcription
	}
	return ""
}

// 富文本消息内容
type RichTextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // markdown, html
	RawContent    string                 `protobuf:"bytes,2,opt,name=raw_content,json=rawContent,proto3" json:"raw_content,omitempty"`
	HtmlContent   string                 `protobuf:"bytes,3,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichTextContent) Reset() {
	*x = RichTextContent{}
	mi := &file_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichTextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichTextContent) ProtoMessage() {}

func (x *RichTextContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichTextContent.ProtoReflect.Descriptor instead.
func (*RichTextContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{24}
}

func (x *RichTextContent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RichTextContent) GetRawContent() string {
	if x != nil {
		return x.RawContent
	}
	return ""
}

func (x *RichTextContent) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

// 系统消息内容
type SystemContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // user_joined, user_left, room_created, etc.
	EventData     map[string]string      `protobuf:"bytes,2,rep,name=event_data,json=eventData,proto3" json:"event_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemContent) Reset() {
	*x = SystemContent{}
	mi := &file_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemContent) ProtoMessage() {}

func (x *SystemContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemContent.ProtoReflect.Descriptor instead.
func (*SystemContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{25}
}

func (x *SystemContent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SystemContent) GetEventData() map[string]string {
	if x != nil {
		return x.EventData
	}
	return nil
}

// ACK消息内容
type AckContent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AckContent) Reset() {
	*x = AckContent{}
	mi := &file_message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckContent) ProtoMessage() {}

func (x *AckContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckContent.ProtoReflect.Descriptor instead.
func (*AckContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{26}
}

func (x *AckContent) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *AckContent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckContent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x05im.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x0eMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.im.v1.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.im.v1.MessageRequest.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x03\n" +
	"\x0fMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.im.v1.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.im.v1.MessageResponse.MetadataEntryR\bmetadata\x12!\n" +
	"\fack_required\x18\b \x01(\bR\vackRequired\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x02\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.im.v1.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.im.v1.SendMessageRequest.MetadataEntryR\bmetadata\x12!\n" +
	"\fack_required\x18\x06 \x01(\bR\vackRequired\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x06status\x18\x03 \x01(\v2\x15.im.v1.ResponseStatusR\x06status\"\xc2\x01\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.im.v1.JoinRoomRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\x10JoinRoomResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.im.v1.ResponseStatusR\x06status\x12,\n" +
	"\troom_info\x18\x02 \x01(\v2\x0f.im.v1.RoomInfoR\broomInfo\x12!\n" +
	"\fonline_users\x18\x03 \x03(\tR\vonlineUsers\"D\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"B\n" +
	"\x11LeaveRoomResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.im.v1.ResponseStatusR\x06status\"F\n" +
	"\x12GetRoomInfoRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x99\x01\n" +
	"\x13GetRoomInfoResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.im.v1.ResponseStatusR\x06status\x12,\n" +
	"\troom_info\x18\x02 \x01(\v2\x0f.im.v1.RoomInfoR\broomInfo\x12%\n" +
	"\x05users\x18\x03 \x03(\v2\x0f.im.v1.RoomUserR\x05users\"\xc0\x02\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x06config\x18\x04 \x01(\v2\x11.im.v1.RoomConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vlast_active\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x12#\n" +
	"\rmessage_count\x18\a \x01(\x03R\fmessageCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\b \x01(\x05R\tuserCount\"\x9d\x02\n" +
	"\n" +
	"RoomConfig\x12\x1b\n" +
	"\tmax_users\x18\x01 \x01(\x05R\bmaxUsers\x12\x1e\n" +
	"\n" +
	"persistent\x18\x02 \x01(\bR\n" +
	"persistent\x12.\n" +
	"\x13message_ttl_seconds\x18\x03 \x01(\x03R\x11messageTtlSeconds\x120\n" +
	"\x14idle_timeout_seconds\x18\x04 \x01(\x03R\x12idleTimeoutSeconds\x12\x1f\n" +
	"\vallow_audio\x18\x05 \x01(\bR\n" +
	"allowAudio\x12&\n" +
	"\x0fallow_rich_text\x18\x06 \x01(\bR\rallowRichText\x12'\n" +
	"\x0fauto_transcribe\x18\a \x01(\bR\x0eautoTranscribe\"\xb3\x01\n" +
	"\bRoomUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12#\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0f.im.v1.UserRoleR\x04role\x12\x14\n" +
	"\x05muted\x18\x04 \x01(\bR\x05muted\x127\n" +
	"\tjoined_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"G\n" +
	"\x11TranscriptRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x7f\n" +
	"\x12TranscriptResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.im.v1.ResponseStatusR\x06status\x12:\n" +
	"\rtranscription\x18\x02 \x01(\v2\x14.im.v1.TranscriptionR\rtranscription\"\x85\x02\n" +
	"\rTranscription\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.im.v1.TranscriptStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"h\n" +
	"\x12UploadAudioRequest\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.im.v1.AudioMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x89\x01\n" +
	"\rAudioMetadata\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\"|\n" +
	"\x13UploadAudioResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.im.v1.ResponseStatusR\x06status\x12\x19\n" +
	"\baudio_id\x18\x02 \x01(\tR\aaudioId\x12\x1b\n" +
	"\taudio_url\x18\x03 \x01(\tR\baudioUrl\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\\\n" +
	"\x13HealthCheckResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.im.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb8\x01\n" +
	"\x0eResponseStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\adetails\x18\x03 \x03(\v2\".im.v1.ResponseStatus.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xb4\x01\n" +
	"\fAudioContent\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x1b\n" +
	"\taudio_url\x18\x02 \x01(\tR\baudioUrl\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12$\n" +
	"\rtranscription\x18\x06 \x01(\tR\rtranscription\"x\n" +
	"\x0fRichTextContent\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vraw_content\x18\x02 \x01(\tR\n" +
	"rawContent\x12!\n" +
	"\fhtml_content\x18\x03 \x01(\tR\vhtmlContent\"\xb0\x01\n" +
	"\rSystemContent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12B\n" +
	"\n" +
	"event_data\x18\x02 \x03(\v2#.im.v1.SystemContent.EventDataEntryR\teventData\x1a<\n" +
	"\x0eEventDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\n" +
	"AckContent\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*\xfa\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_AUDIO\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_TYPE_RICH_TEXT\x10\x03\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x04\x12\x14\n" +
	"\x10MESSAGE_TYPE_ACK\x10\x05\x12\x1a\n" +
	"\x16MESSAGE_TYPE_JOIN_ROOM\x10\x06\x12\x1b\n" +
	"\x17MESSAGE_TYPE_LEAVE_ROOM\x10\a\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\b*g\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x17\n" +
	"\x13USER_ROLE_MODERATOR\x10\x02\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x03*\xb5\x01\n" +
	"\x10TranscriptStatus\x12!\n" +
	"\x1dTRANSCRIPT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRANSCRIPT_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cTRANSCRIPT_STATUS_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bTRANSCRIPT_STATUS_COMPLETED\x10\x03\x12\x1c\n" +
	"\x18TRANSCRIPT_STATUS_FAILED\x10\x04*\x8a\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x02\x12!\n" +
	"\x1dHEALTH_STATUS_SERVICE_UNKNOWN\x10\x032\xb2\x04\n" +
	"\tIMService\x12C\n" +
	"\x0eStreamMessages\x12\x15.im.v1.MessageRequest\x1a\x16.im.v1.MessageResponse(\x010\x01\x12D\n" +
	"\vSendMessage\x12\x19.im.v1.SendMessageRequest\x1a\x1a.im.v1.SendMessageResponse\x12;\n" +
	"\bJoinRoom\x12\x16.im.v1.JoinRoomRequest\x1a\x17.im.v1.JoinRoomResponse\x12>\n" +
	"\tLeaveRoom\x12\x17.im.v1.LeaveRoomRequest\x1a\x18.im.v1.LeaveRoomResponse\x12D\n" +
	"\vGetRoomInfo\x12\x19.im.v1.GetRoomInfoRequest\x1a\x1a.im.v1.GetRoomInfoResponse\x12I\n" +
	"\x12GetAudioTranscript\x12\x18.im.v1.TranscriptRequest\x1a\x19.im.v1.TranscriptResponse\x12F\n" +
	"\vUploadAudio\x12\x19.im.v1.UploadAudioRequest\x1a\x1a.im.v1.UploadAudioResponse(\x01\x12D\n" +
	"\vHealthCheck\x12\x19.im.v1.HealthCheckRequest\x1a\x1a.im.v1.HealthCheckResponseB1Z/github.com/Dev-Umb/im-grpc-sdk/proto/im/v1;imv1b\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_message_proto_goTypes = []any{
	(MessageType)(0),              // 0: im.v1.MessageType
	(UserRole)(0),                 // 1: im.v1.UserRole
	(TranscriptStatus)(0),         // 2: im.v1.TranscriptStatus
	(HealthStatus)(0),             // 3: im.v1.HealthStatus
	(*MessageRequest)(nil),        // 4: im.v1.MessageRequest
	(*MessageResponse)(nil),       // 5: im.v1.MessageResponse
	(*SendMessageRequest)(nil),    // 6: im.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 7: im.v1.SendMessageResponse
	(*JoinRoomRequest)(nil),       // 8: im.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),      // 9: im.v1.JoinRoomResponse
	(*LeaveRoomRequest)(nil),      // 10: im.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),     // 11: im.v1.LeaveRoomResponse
	(*GetRoomInfoRequest)(nil),    // 12: im.v1.GetRoomInfoRequest
	(*GetRoomInfoResponse)(nil),   // 13: im.v1.GetRoomInfoResponse
	(*RoomInfo)(nil),              // 14: im.v1.RoomInfo
	(*RoomConfig)(nil),            // 15: im.v1.RoomConfig
	(*RoomUser)(nil),              // 16: im.v1.RoomUser
	(*TranscriptRequest)(nil),     // 17: im.v1.TranscriptRequest
	(*TranscriptResponse)(nil),    // 18: im.v1.TranscriptResponse
	(*Transcription)(nil),         // 19: im.v1.Transcription
	(*UploadAudioRequest)(nil),    // 20: im.v1.UploadAudioRequest
	(*AudioMetadata)(nil),         // 21: im.v1.AudioMetadata
	(*UploadAudioResponse)(nil),   // 22: im.v1.UploadAudioResponse
	(*HealthCheckRequest)(nil),    // 23: im.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 24: im.v1.HealthCheckResponse
	(*ResponseStatus)(nil),        // 25: im.v1.ResponseStatus
	(*TextContent)(nil),           // 26: im.v1.TextContent
	(*AudioContent)(nil),          // 27: im.v1.AudioContent
	(*RichTextContent)(nil),       // 28: im.v1.RichTextContent
	(*SystemContent)(nil),         // 29: im.v1.SystemContent
	(*AckContent)(nil),            // 30: im.v1.AckContent
	nil,                           // 31: im.v1.MessageRequest.MetadataEntry
	nil,                           // 32: im.v1.MessageResponse.MetadataEntry
	nil,                           // 33: im.v1.SendMessageRequest.MetadataEntry
	nil,                           // 34: im.v1.JoinRoomRequest.MetadataEntry
	nil,                           // 35: im.v1.ResponseStatus.DetailsEntry
	nil,                           // 36: im.v1.SystemContent.EventDataEntry
	(*timestamppb.Timestamp)(nil), // 37: google.protobuf.Timestamp
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: im.v1.MessageRequest.type:type_name -> im.v1.MessageType
	31, // 1: im.v1.MessageRequest.metadata:type_name -> im.v1.MessageRequest.MetadataEntry
	37, // 2: im.v1.MessageRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: im.v1.MessageResponse.type:type_name -> im.v1.MessageType
	37, // 4: im.v1.MessageResponse.timestamp:type_name -> google.protobuf.Timestamp
	32, // 5: im.v1.MessageResponse.metadata:type_name -> im.v1.MessageResponse.MetadataEntry
	0,  // 6: im.v1.SendMessageRequest.type:type_name -> im.v1.MessageType
	33, // 7: im.v1.SendMessageRequest.metadata:type_name -> im.v1.SendMessageRequest.MetadataEntry
	37, // 8: im.v1.SendMessageResponse.timestamp:type_name -> google.protobuf.Timestamp
	25, // 9: im.v1.SendMessageResponse.status:type_name -> im.v1.ResponseStatus
	34, // 10: im.v1.JoinRoomRequest.metadata:type_name -> im.v1.JoinRoomRequest.MetadataEntry
	25, // 11: im.v1.JoinRoomResponse.status:type_name -> im.v1.ResponseStatus
	14, // 12: im.v1.JoinRoomResponse.room_info:type_name -> im.v1.RoomInfo
	25, // 13: im.v1.LeaveRoomResponse.status:type_name -> im.v1.ResponseStatus
	25, // 14: im.v1.GetRoomInfoResponse.status:type_name -> im.v1.ResponseStatus
	14, // 15: im.v1.GetRoomInfoResponse.room_info:type_name -> im.v1.RoomInfo
	16, // 16: im.v1.GetRoomInfoResponse.users:type_name -> im.v1.RoomUser
	15, // 17: im.v1.RoomInfo.config:type_name -> im.v1.RoomConfig
	37, // 18: im.v1.RoomInfo.created_at:type_name -> google.protobuf.Timestamp
	37, // 19: im.v1.RoomInfo.last_active:type_name -> google.protobuf.Timestamp
	1,  // 20: im.v1.RoomUser.role:type_name -> im.v1.UserRole
	37, // 21: im.v1.RoomUser.joined_at:type_name -> google.protobuf.Timestamp
	25, // 22: im.v1.TranscriptResponse.status:type_name -> im.v1.ResponseStatus
	19, // 23: im.v1.TranscriptResponse.transcription:type_name -> im.v1.Transcription
	2,  // 24: im.v1.Transcription.status:type_name -> im.v1.TranscriptStatus
	37, // 25: im.v1.Transcription.created_at:type_name -> google.protobuf.Timestamp
	37, // 26: im.v1.Transcription.updated_at:type_name -> google.protobuf.Timestamp
	21, // 27: im.v1.UploadAudioRequest.metadata:type_name -> im.v1.AudioMetadata
	25, // 28: im.v1.UploadAudioResponse.status:type_name -> im.v1.ResponseStatus
	3,  // 29: im.v1.HealthCheckResponse.status:type_name -> im.v1.HealthStatus
	35, // 30: im.v1.ResponseStatus.details:type_name -> im.v1.ResponseStatus.DetailsEntry
	36, // 31: im.v1.SystemContent.event_data:type_name -> im.v1.SystemContent.EventDataEntry
	4,  // 32: im.v1.IMService.StreamMessages:input_type -> im.v1.MessageRequest
	6,  // 33: im.v1.IMService.SendMessage:input_type -> im.v1.SendMessageRequest
	8,  // 34: im.v1.IMService.JoinRoom:input_type -> im.v1.JoinRoomRequest
	10, // 35: im.v1.IMService.LeaveRoom:input_type -> im.v1.LeaveRoomRequest
	12, // 36: im.v1.IMService.GetRoomInfo:input_type -> im.v1.GetRoomInfoRequest
	17, // 37: im.v1.IMService.GetAudioTranscript:input_type -> im.v1.TranscriptRequest
	20, // 38: im.v1.IMService.UploadAudio:input_type -> im.v1.UploadAudioRequest
	23, // 39: im.v1.IMService.HealthCheck:input_type -> im.v1.HealthCheckRequest
	5,  // 40: im.v1.IMService.StreamMessages:output_type -> im.v1.MessageResponse
	7,  // 41: im.v1.IMService.SendMessage:output_type -> im.v1.SendMessageResponse
	9,  // 42: im.v1.IMService.JoinRoom:output_type -> im.v1.JoinRoomResponse
	11, // 43: im.v1.IMService.LeaveRoom:output_type -> im.v1.LeaveRoomResponse
	13, // 44: im.v1.IMService.GetRoomInfo:output_type -> im.v1.GetRoomInfoResponse
	18, // 45: im.v1.IMService.GetAudioTranscript:output_type -> im.v1.TranscriptResponse
	22, // 46: im.v1.IMService.UploadAudio:output_type -> im.v1.UploadAudioResponse
	24, // 47: im.v1.IMService.HealthCheck:output_type -> im.v1.HealthCheckResponse
	40, // [40:48] is the sub-list for method output_type
	32, // [32:40] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[16].OneofWrappers = []any{
		(*UploadAudioRequest_Metadata)(nil),
		(*UploadAudioRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
